### ISSUE TITLE
Can't connect to a Azure datalake Gen 1 store with Azure managed identity authentication

### ISSUE THREAD

**Issue by adriencoa** [jongio/azidext#31]
As recommended by MS Azure Python SDK Documentation, I tried to use https://gist.github.com/lmazuel/cc683d82ea1d7b40208de7c9fc8de59d credWrapper made by @lmazuel, in my py program to authenticate from an Azure CentOS VM (with managed identity) to access to a Azure Datalake repo, based on Azure Python SDK (especially azure.datalake.store.core.AzureDLFileSystem feature).
@lmazuel told me to use this repo instead of credWrapper, but same result.

Here is my code :

```
from azure_identity_credential_adapter import AzureIdentityCredentialAdapter
from azure.datalake.store import core, lib, multithread
credential = AzureIdentityCredentialAdapter()
adl = core.AzureDLFileSystem(token=credential, store_name = "<NAME OF MY DATALAKE STORE>")
print(adl.walk('<NAME OF A FOLDER AT ROOT OF MY DATALAKE STORE>'))
```

-> I have no output and the program retries infinitely at the adl.walk step.

However, when I use a default authentication strategy (with tenant_id, client_id, secret_id) it works. For example this works:

```
from azure.datalake.store import core, lib, multithread
token = lib.auth(tenant_id = azrTenantId, client_secret = azrSClientId, client_id = azrClientId)
adl = core.AzureDLFileSystem(token, store_name = azrStore)
for i in adl.ls(obj):
   print(i)

```
Is their any mistake in my code ?
Would you have examples to use your program in a DataLake context **with Azure managed identity authentication**?
Thanks!

**Comment by jongio** [comment]
@adriencoa - Do you want to do a call on this?  It would take a while for me to get all that setup, so probably easier for us to just screenshare and figure it out.  You can contact me here: https://jong.io/contact

**Comment by jongio** [comment]
Here's what I got working.  Offer still stands to pair with you on it.

You build up your own chain of credential types you want to use and pass that to AzureIdentityCredentialAdapter.

```
from azure_identity_credential_adapter import AzureIdentityCredentialAdapter
from azure.datalake.store import core, lib, multithread
from azure.identity import (
    AzureCliCredential,
    ChainedTokenCredential,
    ManagedIdentityCredential,
)

credential = AzureIdentityCredentialAdapter(
    ChainedTokenCredential(AzureCliCredential(), ManagedIdentityCredential()),
    "https://management.core.windows.net/",
)

adl = core.AzureDLFileSystem(token=credential, store_name="jong")
adl.mkdir("/test3")

```

**Comment by jongio** [comment]
@adriencoa Did that work?

**Comment by adriencoa** [comment]
Yes it works ! Thank you for your help @jongio !
Sorry for my late answer.

Just one slight change : when trying to load `from azure.identity AzureCliCredential` I had this error : `ImportError: cannot import name 'AzureCliCredential' from 'azure.identity'`

So finally I justed used the ManagedIdentityCredential like this :

```
from azure_identity_credential_adapter import AzureIdentityCredentialAdapter
from azure.datalake.store import core, lib, multithread
from azure.identity import ManagedIdentityCredential

credential = AzureIdentityCredentialAdapter(ManagedIdentityCredential(), "https://management.core.windows.net/")

adl = core.AzureDLFileSystem(token=credential, store_name="STORE")

for i in adl.ls('FOLDER'):
       print(i)
```

Cheers,

Adrien

**Comment by jongio** [comment]
Cool. AzureCliCredential is in the latest preview. It's nice because you can use your CLI login as you local dev experience credential and then MI when you ship to prod without any code changes. 

https://aka.ms/azsdk/releases to find the previews.
