### ISSUE TITLE
[python] Unable to create ACI 

### ISSUE THREAD

**Issue by urucoder** [jongio/azidext#39]
Requirements:

- azure-mgmt-containerinstance==7.0.0
- azure-mgmt-resource==15.0.0
- AzureIdentityCredentialAdapter

Error message:

> 'AzureIdentityCredentialAdapter' object has no attribute 'get_token'

I tracked the explosion to the file _container_groups_operations.py in the line 

> pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)

Let you a piece of code of how I'm using it.
`   

    from .azure_identity_credential_adapter import AzureIdentityCredentialAdapter
    from azure.mgmt.resource import SubscriptionClient
    from azure.mgmt.containerinstance import ContainerInstanceManagementClient

    credential = AzureIdentityCredentialAdapter()
    subscription_client = SubscriptionClient(credential)
    subscription = next(subscription_client.subscriptions.list())
    aciclient = ContainerInstanceManagementClient(credential, subscription.subscription_id)
    cgname = "test-image"
    job_payload["aci_name"] = cgname

    # create container
    container_resource_requests = ResourceRequests(memory_in_gb=16, cpu=4.0)
    container_resource_requirements = ResourceRequirements(requests=container_resource_requests)

    container = Container(name=cgname,
                          image="testimage",
                          resources=container_resource_requirements,
                          command=["sh", "-c", "python3 /app/test-script.py"])

    # Configure the container group
    group = ContainerGroup(containers=[container],
                           os_type=OperatingSystemTypes.linux,
                           restart_policy=ContainerGroupRestartPolicy.on_failure)
    aciclient.container_groups.begin_create_or_update(resource_group.name, cgname, group)
`

Let me know if I can add more info on this, thanks.

**Comment by lmazuel** [comment]
Hi @urucoder !

If SDK requires `get_token` (which is your error), it means you don't need an azure-identity wrapper :). Both these SDKs were migrated to support azure-identity recently.
