### ISSUE TITLE
AzureIdentityFluentCredentialAdapter for fluent ActiveDirectory: Unauthorized

### ISSUE THREAD

**Issue by Willem-J-an** [jongio/azidext#40]
Managed to get the AzureIdentityFluentCredentialAdapter to work for Azure, I can succesfully retrieve resources and use Fluent SDK, awesome stuff!
Only problem I ran into is I can't seem to make requests to Azure AD. I do have permissions to read users in the directory with this acocunt.

```
AzureCredentials creds = new AzureIdentityFluentCredentialAdapter(
                "tenant",
                AzureEnvironment.AzureGlobalCloud
            );
var authenticated = Microsoft.Azure.Management.Fluent.Azure
                .Configure()
                .Authenticate(creds);
            Console.WriteLine(
                JsonSerializer.Serialize(
                    authenticated.ActiveDirectoryUsers.GetByName("name")
                )
            );
```
```
Unhandled exception. Microsoft.Azure.Management.Graph.RBAC.Fluent.Models.GraphErrorException: Operation returned an invalid status code 'Unauthorized'
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.ActiveDirectoryUsersImpl.GetByNameAsync(String name, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.Graph.RBAC.Fluent.ActiveDirectoryUsersImpl.Microsoft.Azure.Management.ResourceManager.Fluent.Core.CollectionActions.ISupportsGettingByName<Microsoft.Azure.Management.Graph.RBAC.Fluent.IActiveDirectoryUser>.GetByName(String name)
```
Any ideas how I can make this work? Thanks in advance!

**Comment by jongio** [comment]
I'm glad you got it working.  For the perm issue, we'll follow up in a different way.  Can you contact me here so I can help you get help?  https://jong.io/contact

**Comment by jongio** [comment]
Going to close this for now since you can contact me at above location.

**Comment by jongio** [comment]
This may help: https://devblogs.microsoft.com/azure-sdk/azure-identity-with-sql-graph-ef/

**Comment by Willem-J-an** [comment]
Hi @jongio,
Thanks for getting back to me. The article linked seems to use the default credential for Azure, which I'm able to do. Further, it uses the credential to create a token to use for SQL, while I might be able to generate a token like this to invoke graph/AAD api to retrieve AD users, I suppose I wouldn't be able to use this token together with the Fluent SDK method. I submitted a form to the link above but haven't heard back yet. Let me know if there are any other options to try!

**Comment by jongio** [comment]
@Willem-J-an  - Can you please file an issue here: https://aka.ms/netsdk?
