### ISSUE TITLE
Publish to package mangers

### ISSUE THREAD

**Issue by allanlw** [jongio/azidext#43]
The README says:

> The classes contained in this repo are only meant to be a temporary stopgap between now and when the Resource Management, Fluent, and Service Bus SDKs support Azure.Core. Since those efforts are currently underway, we think it would be best for you to copy the classes in this project to your class instead of releasing them via a package manager.

>The Azure Management libraries will be updated to support Azure Identity and Azure Core in early 2020, so this should just be used a a stopgap between now and then.

However, so far it would seem that this transition is still in progress, so there would be utility to publishing these classes somewhere they could be consumed without copy and pasting.

**Comment by jongio** [comment]
@allanlw - I'm researching this.  Can you let me know what libraries you used that required this adapter?

**Comment by allanlw** [comment]
Thanks @jongio - `Microsoft.Azure.Management.Consumption` and `Microsoft.Azure.Management.CognitiveServices` both do not have corresponding releases that use the Azure dotnet core.

**Comment by jongio** [comment]
Thanks for that and the original feedback.  We are still considering options.  We are close on getting all packages upgraded, so need to consider supportability promise for future.

**Comment by allanlw** [comment]
Definitely understand. Vending the code in my own package though seems like the worst of both worlds.

The C# code is only a few classes, I wouldn't mind if it was published to nuget as a one-off in a non-official namespace. After all, the code _already_ doesn't have a supportability promise, and publishing it somewhere else doesn't necessarily have to be tied to providing one.

**Comment by jongio** [comment]
We are getting close to releasing Azure Identity support for management libs, so I prefer to keep this code as a sample to not have future NuGet management considerations.
