### ISSUE TITLE
Wrapper returns token as 'None'

### ISSUE THREAD

**Issue by dmartin-r7** [jongio/azidext#49]
I am trying to use this wrapper to create a ClientSecretCredential object that can be used with old and new. I have copied the exact code and passed in the secret, tenant and api key to the wrapper (to pass to the ClientSecretCredential) but this does not work.

I get the following:

`AttributeError: 'CredentialWrapper' object has no attribute 'get_token'` - This is with the ResourceGraphClient.

When debugging, regardless of the Client I use, the token attribute is always None.

Even using the defaultazurecredential returns a none token value.

**Comment by jongio** [comment]
.NET right?

**Comment by dmartin-r7** [comment]
Python sorry, should have specified

**Comment by v-xuto** [comment]
@dmartin-r7  What version of package `azure-mgmt-resourcegraph` are you using?
1. If you are using the package `azure-mgmt-resourcegraph` version before 2.0.0 (including 2.0.0), you can use the `AzureIdentityCredentialAdapter` in azidext. I tested it locally and it works fine.
2. If you are using the package `azure-mgmt-resourcegraph` version after 7.0.0b1 (including 7.0.0b1), you can use `DefaultAzureCredential` or `ClientSecretCredential` in `azure-identity` directly, the detailed code is as follows:

```
import os
from azure.identity import DefaultAzureCredential
from azure.mgmt.resourcegraph import ResourceGraphClient

resourcegraph_client = ResourceGraphClient(
    credential=DefaultAzureCredential(),
    subscription_id=os.getenv("AZURE_SUBSCRIPTION_ID")
)
```
The `AzureIdentityCredentialAdapter` class allows you to use all the goodness of `Azure.Identity.DefaultAzureCredential` in the Azure Management libraries. The `AzureIdentityCredentialAdapter` class provides a simple adapter to use any credential from `azure-identity` with any SDK that accepts credentials from `azure.common.credentials` or `msrestazure.azure_active_directory`. The Azure Management Library has been updated to support Azure Identity and Azure Core in early 2020, so it was just a stopgap measure at the time.

So, for the recently released mgmt sdk, azure identity can be used directly without the need for the adapter in this repo.

If you have any questions please let me know.

**Comment by v-xuto** [comment]
@dmartin-r7  Has your issue been solved again? Please let me know if there are any problems. If resolved, we will close this issue.

**Comment by dmartin-r7** [comment]
Hi, I resolved this but I had to modify the wrapper a fair bit. I had to call set_token in the init and also the returned token was missing an expires on parameter. Also had to write a custom get_token method too but working now.

**Comment by jongio** [comment]
@dmartin-r7 - I would greatly appreciate it if you could PR your changes into this repo.  No worries if no time.  But it would be great if you could.
